# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=50)),
                ('hip_name', models.CharField(max_length=50)),
                ('hd_name', models.CharField(max_length=50)),
                ('gj_name', models.CharField(max_length=50)),
                ('planets_in_system', models.IntegerField()),
                ('distance', models.FloatField()),
                ('distance_plus', models.FloatField(null=True)),
                ('distance_minus', models.FloatField(null=True)),
                ('v_band_mag', models.FloatField()),
                ('v_band_mag_plus', models.FloatField(null=True)),
                ('v_band_mag_minus', models.FloatField(null=True)),
                ('b_v_mag', models.FloatField()),
                ('b_v_mag_plus', models.FloatField(null=True)),
                ('b_v_mag_minus', models.FloatField(null=True)),
                ('spectral_type', models.CharField(max_length=10)),
                ('stellar_bm_lumo', models.FloatField()),
                ('stellar_bm_lumo_plus', models.FloatField(null=True)),
                ('stellar_bm_lumo_minus', models.FloatField(null=True)),
            ],
        ),
    ]
